# -*- coding: utf-8 -*-
"""
Created on Tue Sep 15 15:39:43 2020

@author: LocalAdmin
"""
'''%%%%%%%%%%%%%%%%%%%%%%%%%% CODE DESCRIPTION %%%%%%%%%%%%%%%%%%%%%%%%%%%%%'''
'''
Run this script to copy raw data (generated by the cx7 high content microscope)
from the N (staff bulk) drive to the M (staff groups) drive. The script will 
combine different color channels into one stack of images. Also, it will rename
the tiles from a spiral grid into a column-grid which is convenient for stitching.
'''


'''%%%%%%%%%%%%%%%%%%%%%%%%% PARAMETERS TO SET %%%%%%%%%%%%%%%%%%%%%%%%%%%%%'''

# path to raw experiment data folder, use forward slashes (/)
raw = 'N:/tnw/BN/dm/Shared/Kasper/Experiments/WKS025/20x/MFGTMP_13_07_30'

# path to experiment data analysis folder, use forward slashes (/)
root = 'M:/tnw/bn/dm/Shared/Lukas/BEP/Experiments/WKS025/20x'

# list of wells you want to analyse
well_list = ['B03']
            
 # number of tiles in one dimension (the total number of tiles in the image is w*w)
w = 15

# number of color channels in each image.
n_channels = 3

'''%%%%%%%%%%%%%%%%%%%%%%%%%%%%% START CODE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'''

import os
from Helpers.prepare_stitch_helpers import prepare_dataset_for_stitching

# Create root directory, if it does not exist already
if not os.path.exists( root ):
    os.mkdir(  root )
    print("Created a new root folder for this experiment.")
# Make a tile folder for each well inside root
prepare_dataset_for_stitching(raw, root, well_list, w, n_channels)
print("Finished preparation, you can now start the stitching procedure in FIJI.")